[package]
name = "brhap-server"
version = "0.1.1"
edition = "2024"

[dependencies]
nix = { version = "0.31.3", features = ["signal"] }
regex = "1.13.1"
reqwest = { version = "0.13.4", features = ["blocking", "gzip", "deflate"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
